<?xml version="1.0" encoding="utf-8"?><Database Name="HumaneSociety" Class="HumaneSocietyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-BFH6QG7;Initial Catalog=HumaneSociety;Integrated Security=True" SettingsObjectName="HumaneSociety.Properties.Settings" SettingsPropertyName="HumaneSocietyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Small_Animals" Member="Small_Animals">
    <Type Name="Small_Animal">
      <Column Name="Animal_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Animal_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Animal_Type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Animal_Size" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Aniaml_Shots" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Animal_Room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Food_Amount" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Animal_Adopter" Member="Animal_Adopters">
    <Type Name="Animal_Adopter">
      <Column Name="Adopter_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Animal_Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Adopter_Money" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cat" Member="Cats">
    <Type Name="Cat">
      <Column Name="Cat_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Breed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="size" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="shots" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Cat_status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Food_Amount" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="Doctor_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Employee_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dog" Member="Dogs">
    <Type Name="Dog">
      <Column Name="Dog_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Breed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="size" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="shots" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Dog_status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Food_Amount" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>